name: Publish to Maven Central

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  publish:
    runs-on: faster-linux

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew :counter-client:test
