name: Publish to Maven Central

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: faster-linux

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Run tests
        run: ./gradlew :counter-client:test

      - name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.SIGNING_KEY_SECRET_ARMOR_EXPORT }}") | gpg --batch --import

      - name: List gpg secret keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Create output directory
        run: mkdir -p /home/runner/work/counter

      - name: Export gpg secret key
        run: gpg --export-secret-keys --pinentry-mode loopback --passphrase=${{ secrets.SIGNING_KEY_PASSWORD }} ${{ secrets.SIGNING_KEY_ID }} > /home/runner/work/counter/secring.gpg

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Sonatype
        run: ./gradlew publishAllPublicationsToSonatypeRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY_LOCATION: /home/runner/work/counter/secring.gpg
